version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - '8000:80'
    depends_on:
      - django_server
    volumes:
      - ./server/mysite/static:/static
  django_server:
    build:
      context: ./server
    volumes:
      - ./server/mysite/static:/static
